Rails.application.config.assets.precompile += %w( d3.geom.js jquery.history.js raphael.js vis4.js Tween.js bubbletree.js cofog.js )
Rails.application.config.assets.precompile += %w( biPartite.js sankey.js )
Rails.application.config.assets.precompile += %w( d3pie.js )
Rails.application.config.assets.precompile += %w( jstree/jstree.js jstree/themes/default/style.min.css)
Rails.application.config.assets.precompile += %w( timelinejs/storyjs-embed.js timelinejs/timeline.js timelinecss/timeline.css )
Rails.application.config.assets.precompile += %w( kartik-fileinput/js/fileinput.js kartik-fileinput/js/fileinput_locale_uk.js kartik-fileinput/css/fileinput.css )

Rails.application.config.assets.precompile += %w( leaflet/leaflet.js leaflet/leaflet.css )
Rails.application.config.assets.precompile += %w( leaflet/markercluster.js leaflet/markercluster.default.css leaflet/markercluster.css )
Rails.application.config.assets.precompile += %w( leaflet/zoomfs.js )
Rails.application.config.assets.precompile += %w( leaflet/leaflet.js leaflet/leaflet.css leaflet/leaflet-routing-machine.js leaflet/leaflet-routing-machine.css )
Rails.application.config.assets.precompile += %w( html2canvas/html2canvas.js html2canvas/html2canvas.svg.js )
